import { readdirSync, readFileSync, renameSync, writeFileSync } from "node:fs";
import { join } from "node:path";

// Generate src/assets.ts with embedded file contents
function generateAssets() {
  const agentsMd = readFileSync("AGENTS.md", "utf-8");

  const skills: Record<string, string> = {};
  collectMdFiles("src/skills", skills);

  const rules: Record<string, string> = {};
  collectMdFiles("src/rules", rules);

  const code = `// Auto-generated by build.ts — do not edit
export const AGENTS_MD = ${JSON.stringify(agentsMd)};

export const SKILLS: Record<string, string> = ${JSON.stringify(skills, null, 2)};

export const RULES: Record<string, string> = ${JSON.stringify(rules, null, 2)};
`;

  writeFileSync("src/assets.ts", code);
  console.log("Generated src/assets.ts");
}

function collectMdFiles(dir: string, out: Record<string, string>, prefix = "") {
  const entries = readdirSync(dir, { withFileTypes: true });
  for (const entry of entries) {
    const full = join(dir, entry.name);
    const key = prefix ? `${prefix}/${entry.name}` : entry.name;
    if (entry.isDirectory()) {
      collectMdFiles(full, out, key);
    } else if (entry.name.endsWith(".md")) {
      out[key] = readFileSync(full, "utf-8");
    }
  }
}

// Generate assets then build
generateAssets();

const result = await Bun.build({
  entrypoints: ["./src/cli/index.ts"],
  outdir: "./dist",
  target: "bun",
  compile: true,
  minify: true,
  external: ["react-devtools-core"],
});

if (!result.success) {
  console.error("Build failed:");
  for (const log of result.logs) {
    console.error(log);
  }
  process.exit(1);
}

renameSync("./dist/cli", "./dist/paikea");
console.log("Build successful! Binary at dist/paikea");
