import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import type { ProjectConfig } from "../types";

export function generateProjectStructure(config: ProjectConfig) {
  const projectDir = config.name;
  mkdirSync(join(projectDir, "src"), { recursive: true });
  mkdirSync(join(projectDir, ".claude", "skills"), { recursive: true });
  mkdirSync(join(projectDir, "openspec", "specs"), { recursive: true });

  const packageJson = generatePackageJson(config);
  writeFileSync(
    join(projectDir, "package.json"),
    `${JSON.stringify(packageJson, null, 2)}\n`,
  );

  const readme = generateReadme(config);
  writeFileSync(join(projectDir, "README.md"), readme);

  const gitignore = generateGitignore(config);
  writeFileSync(join(projectDir, ".gitignore"), gitignore);
}

function generatePackageJson(config: ProjectConfig): Record<string, unknown> {
  const scripts: Record<string, string> = {};

  switch (config.lang) {
    case "typescript":
      scripts.dev = "bun run src/index.ts";
      scripts.build = "bun build src/index.ts --outdir dist";
      scripts.start = "bun run dist/index.js";
      break;
    case "python":
      scripts.dev = "python -m uvicorn src.main:app --reload";
      scripts.start = "python -m uvicorn src.main:app";
      break;
    case "go":
      scripts.dev = "go run .";
      scripts.build = "go build -o dist/app .";
      scripts.start = "./dist/app";
      break;
    case "rust":
      scripts.dev = "cargo run";
      scripts.build = "cargo build --release";
      scripts.start = "./target/release/app";
      break;
    default:
      scripts.dev = "echo 'Configure your dev script'";
  }

  return {
    name: config.name,
    version: "0.1.0",
    private: true,
    scripts,
  };
}

function generateReadme(config: ProjectConfig): string {
  return `# ${config.name}

Generated by paikea.

## Stack

- **Language:** ${config.lang}
- **Framework:** ${config.framework}
- **Database:** ${config.database.join(", ") || "None"}
- **Services:** ${config.services.join(", ") || "None"}

## Getting Started

\`\`\`bash
# In devcontainer
paikea

# Or manually
bun run dev
\`\`\`

## OpenSpec

This project uses OpenSpec for spec-driven development.

\`\`\`bash
# In your AI chat:
/opsx:explore
/opsx:propose my-feature
\`\`\`
`;
}

function generateGitignore(config: ProjectConfig): string {
  let gitignore = `node_modules/\ndist/\n.env\n.env.local\n`;

  if (
    config.database.includes("postgres") ||
    config.database.includes("mysql")
  ) {
    gitignore += `*.db\n`;
  }
  if (config.database.includes("mongodb")) {
    gitignore += `data/\n`;
  }

  gitignore += `
# OS
.DS_Store
Thumbs.db

# IDE
.vscode/
.idea/

# paikea
.paikea/
`;

  return gitignore;
}
